apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: flink

resources:
  - cmfrestclass.yaml
  - flink-environment.yaml
  - flink-application.yaml
  - service.yaml
  - servicemonitor.yaml
  - grafana-dashboard.yaml

# Common labels applied to all resources
labels:
- includeSelectors: false
  includeTemplates: true  
  pairs:
    app.kubernetes.io/part-of: confluent-flink
    app.kubernetes.io/managed-by: argocd
