apiVersion: v1
kind: Service
metadata:
  labels:
    platform.confluent.io/origin: manual
    type: flink-native-kubernetes
  name: flink-pods
spec:
  ports:
  - name: metrics
    port: 9249
    protocol: TCP
    targetPort: 9249
  selector:
    platform.confluent.io/origin: flink
    type: flink-native-kubernetes
  type: ClusterIP
