---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: vault-server
  namespace: vault
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`vault.CLUSTER_NAME.DOMAIN`)
      kind: Rule
      services:
        - name: vault
          port: 8200
  tls:
    secretName: vault-server-tls
