---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: controlcenter
  namespace: kafka
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`controlcenter.CLUSTER_NAME.DOMAIN`)
      kind: Rule
      services:
        - name: controlcenter
          port: 9021
          scheme: http
  tls:
    secretName: controlcenter-tls
