---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

patches:
  - path: ingressroute-patch.yaml
    target:
      kind: IngressRoute
      name: vault-server
  - path: certificate-patch.yaml
    target:
      kind: Certificate
      name: vault-server-tls
